### ISSUE TITLE
Stylistic sets defaults are not the same in variable and static files

### ISSUE THREAD

**Issue by fpalaci** [arrowtype/name-sans-roadmap#33]
I noticed I am getting differents glyphs with the same stylistic set activated in the variable font and the static fonts.

For instance, if I use font-feature-settings: "ss03":

* The variable font shows a double-storey g
* While the static fonts whow a single-storey g

This is an issue in 2-stages font loading strategies since it makes the text move quite a lot when it lazy loads in.

This is the cas with at least the lowercase G, lowercase L, uppercase I.

I hope this can be changed without to much hassle :-)

Thanks a lot for this great and promising font!

**Comment by arrowtype** [comment]
Hi @fpalaci, thanks for taking the time to file this issue! I'm glad to hear you're making of the stylistic sets.

This is a sensible request, and something I will try to keep in mind as I improve overall stylistic set support with the next release, `v0.5`. It's helpful to keep a specific use-case in mind when approaching something like this!

If you're willing to share, is there a good explanation somewhere of what you mean by a two-stage font loading strategy? I get the general gist, but I'm curious what you might specifically be doing, if it's simple enough to explain.

**Comment by fpalaci** [comment]
Hi @arrowtype,

Thanks for the follow-up!

I plan to implement the strategy presented here: https://www.zachleat.com/web/css-tricks-web-fonts/

First (stage 1), the webpage will load Name Sans Regular and a subset of Name Sans Medium. Then (stage 2) I will load the variable font for extra options it enables (animating links and such things). The idea is to speed up the first text paint (with small-sized files) and then seamlessly swap to the full font.

When I do it with the v0.4 files, the text moves when the swap happens (when the variable font is loaded and replaces the static fonts) since the stylistic sets codes are not the same in the static and variable fonts.

**Comment by arrowtype** [comment]
Nice!

Question: since you are already loading fonts in with JavaScript, could you potentially also adjust the `font-feature-settings` CSS at the same time? I realize this isn’t ideal, and I will hopefully be able to simplify this with the next release (or perhaps sooner, but I can’t really make any promises, due to other ongoing client work).

---

PS: One thing that might be worth adding to your font strategy is to use [`unicode-range` subsetting](https://css-tricks.com/almanac/properties/u/unicode-range/) to improve loading even more. 

Basically, you can make a subset that covers _just_ the primary language support you will have on the website, then make other subsets with remaining characters, and these will load in secondarily, and only if actually required. This is an approach Google Fonts uses for fonts with Vietnamese characters, for example.

Here’s a script I’ve made to set this up for Recursive:

https://github.com/arrowtype/recursive/blob/e2d9ef51b7ed2f19f8cfdddcedf6b21b590666e2/src/build-scripts/make-release/make-variable-woff2s_and_subsets.sh#L31-L52

You could adjust this and run it on the Name Sans fonts, if you want, or I could help more if you’d want assistance.

(Based on the location in your GitHub profile, I’m guessing your website may use French? If so, I would add the required accented characters to the “English Basic” subset.)

A slight variation of this strategy is used at https://sia.codes/, where the heaviest weight of Recursive is only loaded in for the name `sia`:

```css
/* SPECIFICALLY for the 'sia' karamalegos logo @ sia.code – remove if you don't need :) */
@font-face {
  font-family: 'Recursive Sia';
  font-weight: 1000;
  font-display: block;
  src: url('fonts/Recursive_VF_1.034--subset_sia_logo.woff2') format('woff2');
  unicode-range: U+0073,U+0069,U+0061;
}
```

**Comment by fpalaci** [comment]
Yes, I'm pondering whether I should adjust the `font-feature-settings` CSS in my javascript and/or my HTML (I did not think about it, thanks for the tip!) or simply adjust the font's opentype layout tables in the meantime (no worries, I will be happy when you release a new version which might simplify this, but I will find a way for now. I can understand you have more urgent stuff that requires your attention and I also look forward to discovering Name Sans italics).

I'm French but the website will be in English (or maybe both in English and French if I am brave enough).

Thanks for the unicode-subsetting trick (and for the unicode ranges!). I will look into it. It looks promising! It would mean potentially having more HTTP requests though. I will do some tests when I am more advanced in my little project :-)

Thanks again for your help Stephen! If you want me to close this issue, let me know.

**Comment by arrowtype** [comment]
Sounds good! Thanks for understanding, and thanks for your kind words!

> Thanks for the unicode-subsetting trick (and for the unicode ranges!). I will look into it. It looks promising! It would mean potentially having more HTTP requests though. I will do some tests when I am more advanced in my little project :-)

As I understand it, these requests don’t block content, and I think that multiple HTTPS requests don’t have the same impact on performances that HTTP requests once did – I believe this is because authentication only happens once, even for multiple files. But, I am not a web performance expert, so I might be slightly inaccurate here.

Let’s keep the issue open, as I will try to resolve this in one way or another. Thanks again for filing it!

**Comment by arrowtype** [comment]
Okay, I think I’ve found and successfully built a fix for this!  I will include this change with v0.5, but I’ve emailed you the files directly.

If anyone else comes across this and would also like the change, please reach out to me at info at arrowtype.com and I will provide you the patched files.

![image](https://user-images.githubusercontent.com/45946693/108120875-ef18e900-706f-11eb-8f6a-b9c674ffc799.png)

![image](https://user-images.githubusercontent.com/45946693/108120882-f0e2ac80-706f-11eb-9e0b-e14d0034d117.png)

**Comment by fpalaci** [comment]
Awesome! Thanks a lot!
